image: node:10.15.3
pipelines:
  branches:
    master:
      - step:
          script:
            - yarn install
            - yarn build
            - npm install -g firebase-tools
            - yarn deploy
